version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing Composer
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-interaction --no-progress
  pre_build:
    commands:
      - echo Running PHPUnit tests
  build:
    commands:
      - ./vendor/bin/phpunit --configuration phpunit.xml
artifacts:
  files:
    - '**/*'
  discard-paths: yes
