version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies using composer
      - composer install --no-interaction --no-progress
  pre_build:
    commands:
      - echo Running Codeception Unit Tests
  build:
    commands:
      - ./vendor/bin/codecept run Unit --html
artifacts:
  files:
    - '**/*'
  discard-paths: yes
